package game.common;

public class Province {
    private int id;
    private int rgb;
    private Terrain terrainType;
    private String name;

    // TODO: 27/02/2023 change pops using message in #general (sent 11:12 27/2/23)
    private int numOfPeasant;
    private int numOfBurgher;
    private int numOfNobility;
    private int numOfClergy;
    private int numOfBureaucrat;

    private int maxBuildings;
    private int numOfBuildings;
    //derivative province values (generated by pops)
    private float tax;
    private float production;
    private float researchPoints;
    private float importRoutes;
    private float manpower;
    private float sailors;

    public Province(int id, Terrain terrainType, int rgb) {
        this.id = id;
        this.terrainType = terrainType;
        this.rgb = rgb;
    }

    public int getId() {
        return id;
    }

    public Terrain getTerrainType() {
        return terrainType;
    }

    public int getRgb() {
        return rgb;
    }
}
